name: Build Mexican Train for TI-84 Plus CE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CEdev
        uses: CE-Programming/toolchain@master

      - name: Build
        run: make

      - name: Upload 8XP
        uses: actions/upload-artifact@v4
        with:
          name: Mexican-Train-8XP
          path: bin/*.8xp
          if-no-files-found: error
